{% set name = "api-inference-community" %}
{% set version = "0.0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/api_inference_community-{{ version }}.tar.gz
  sha256: f503e2443102ed3fdde0e1adcd84a684a89e98e4839ec2666c7b81002a2e48fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - datasets >=2.2
    - huggingface_hub >=0.5.1
    - numpy >=1.18.0
    - parameterized >=0.8.1
    - pillow >=8.2.0
    - pydantic >=1.8.1
    - python >=3.6
    - starlette >=0.14.2

test:
  imports:
    - api_inference_community
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/huggingface/api-inference-community
  summary: A package with helper tools to build an API Inference docker app for Hugging Face API inference using huggingface_hub
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - adrinjalali
